[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install -g pnpm", "pnpm install"]

[build.nixpacksPlan.phases.build]
cmds = ["echo 'Skipping build'"]

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
